### ISSUE TITLE
Error on steam private server

### ISSUE THREAD

**Issue by jenheilemann** [iKlem/screepsmod-gcltocpu#4]
Trying to use this from the Steam workshop, it halts the local private server with this error:

```
Error while main loop (stage getUsers): TypeError: result.ivm is not iterable
    at promise.then.result (D:\SteamLibrary\steamapps\common\Screeps\server\node_modules\screepsmod-gcltocpu\index.js:31:34)
    at _fulfilled (D:\SteamLibrary\steamapps\common\Screeps\server\package\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (D:\SteamLibrary\steamapps\common\Screeps\server\package\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (D:\SteamLibrary\steamapps\common\Screeps\server\package\node_modules\q\q.js:796:13)
    at D:\SteamLibrary\steamapps\common\Screeps\server\package\node_modules\q\q.js:604:44
    at runSingle (D:\SteamLibrary\steamapps\common\Screeps\server\package\node_modules\q\q.js:137:13)
    at flush (D:\SteamLibrary\steamapps\common\Screeps\server\package\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by AlinaNova21** [comment]
This not have been updated in a while, you may want to look at the cpu scaling options in screepsmod-admin-utils. It also allows you to adjust the values for it.

**Comment by iKlem** [comment]
Hi.
Like @ags131 said, use the screepsmod-admin-utils.
@ags131 , can you archive the repo & close this issue ?
